version: '3.8'

services:
  # Сервис вашего Java-приложения
  app:
    build: .  # Указывает собрать образ из Dockerfile в текущей папке (в корне)
    container_name: my-java-app
    depends_on:
      - pg # Запускать только после того, как запустится сервис pg
    restart: on-failure

  # Сервис базы данных PostgreSQL
  pg:
    image: postgres:14-alpine # Используем готовый образ PostgreSQL
    container_name: postgres-db
    environment:
      # Эти переменные должны совпадать с тем, что ожидает ваше приложение
      POSTGRES_DB: studs
      POSTGRES_USER: s465878
      POSTGRES_PASSWORD: 0pKaKsNIQxLhWHSt
    ports:
      - "5432:5432" # Пробрасываем порт, чтобы можно было подключиться к БД с компьютера
    volumes:
      - postgres-data:/var/lib/postgresql/data # Сохраняет данные БД даже после перезапуска контейнера

volumes:
  postgres-data: # Определяем том для хранения данных